export const careersLink = 'https://apply.workable.com/index-coop/'
export const discordLink = 'https://discord.gg/wlkrfinance'
export const forumLink = 'https://gov.indexcoop.com'
export const handbookLink = 'https://docs.indexcoop.com/'
export const pressKitLink = 'https://docs.indexcoop.com/resources/press-kit'
export const twitterLink = 'https://twitter.com/wlkrfinance'
export const voteLink = 'https://snapshot.org/#/index-coop.eth'
export const websiteLink = 'https://wlkr.finance'
